steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/lokalens-backend'
      - '-f'
      - 'Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/lokalens-backend'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'lokalens-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/lokalens-backend'
      - '--region'
      - 'asia-southeast2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '3'
      - '--set-env-vars'
      - 'GEMINI_API_KEY=AIzaSyBI3xo4VWCHdJnDmqoTerE5Ce8tUZAaFas,GOOGLE_PLACES_API_KEY=AIzaSyDi0ku9_kVg1Y6suedDC9b_7RZXxr1VfXk,FIREBASE_PROJECT_ID=lokalens-web,FIREBASE_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCcBX+ODoFtRx19\n...\n-----END PRIVATE KEY-----\n,FIREBASE_CLIENT_EMAIL=firebase-adminsdk-fbsvc@lokalens-web.iam.gserviceaccount.com'
images:
  - 'gcr.io/$PROJECT_ID/lokalens-backend'